### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by FujiwaraChoki** [inulute/perplexity-ai-app#1]
Hey, first of all, thanks for this project, really helpful!

However, I'm unable to sign in using Google.

It's telling me it's a security issue.

**Comment by inulute** [comment]
Hey, thanks for reporting the issue. I appreciate your feedback. There's another repository called [Ai-Gate](https://github.com/inulute/ai-gate) that not only fixes this problem but also provides access to ChatGPT and Bard. You might want to give that a try.

**Comment by inulute** [comment]
> Hey, first of all, thanks for this project, really helpful!
> 
> However, I'm unable to sign in using Google.
> 
> It's telling me it's a security issue.


Okay, so I have addressed the security issue in version 1.0.0, so you should now be able to sign in using Google without any problems.

**Comment by FujiwaraChoki** [comment]
> > Hey, first of all, thanks for this project, really helpful!
> > However, I'm unable to sign in using Google.
> > It's telling me it's a security issue.
> 
> Okay, so I have addressed the security issue in version 1.0.0, so you should now be able to sign in using Google without any problems.

Thanks, just saw!
