### ISSUE TITLE
Feature request: Block the mobile app nag screens.

### ISSUE THREAD

**Issue by kyods** [inulute/perplexity-ai-app#10]
Hi, would it be possible to block the 'download mobile/Android app' nag screens which tend to show up every now and then? It's probably the most annoying thing about Perplexity, as if they would even allow me to install the iPad app on my Mac (which, in fact, would be quite awesome). It seems there are two types of those nags: one of them asking to install the mobile app which shows up in the default-sized window, and the other, to install the Android app (sic!) when the window is resized to the more or less mobile size.

**Comment by inulute** [comment]
Sure, I can give it a shot.

**Comment by heinhuiz** [comment]
I get another nag screen. I get a pop-up telling me I am logged out every few new queries, which I can close and then continue where I left off, but still it is annoying.

**Comment by inulute** [comment]
> ![Screenshot from 2024-08-05 00-42-27](https://private-user-images.githubusercontent.com/12214714/354990625-eac75106-2af0-4ebc-b325-f38b1093d9e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDMwMjIsIm5iZiI6MTcyMjg0MjcyMiwicGF0aCI6Ii8xMjIxNDcxNC8zNTQ5OTA2MjUtZWFjNzUxMDYtMmFmMC00ZWJjLWIzMjUtZjM4YjEwOTNkOWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA3MjUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhOTYzNDYyYWJhOWNkMWVmNDNkODNjNTNjOTZhYzAwYmIyOGViYTllNWMyZmI1NmQ3ZmQzZGU2ZThiYWI5MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R8xQ4QroSRSEt0PN_uNUEW2YOojsrXz2jLwDeBDwWQM) Note that I also get this screen when I'm using a browser for perplexity.ai.

Okay, I'll see what could be done.

**Comment by heinhuiz** [comment]
Now it's like this:
![Screenshot from 2024-09-15 10-55-49](https://github.com/user-attachments/assets/24c5fd36-efd1-4de1-8394-98fae3d0e25e)

**Comment by inulute** [comment]
Hi! Thanks for your feedback; we get how those prompts can be disruptive.

With **Perplexity AI v3.0.0**, we’ve worked on reducing unnecessary prompts for a smoother experience.

We hope v3.0.0 offers a more seamless experience, and we appreciate your input to help make Perplexity AI even better!
