### ISSUE TITLE
Does it still require refresh?

### ISSUE THREAD

**Issue by rochakagrawal** [inulute/perplexity-ai-app#14]
Thanks for the app. What is the main advantage of it? I simply pin the website to the dock, the issue is that it breaks connection after a while, requiring me to refresh my login and captcha before my query gets answered. Does this app maintain the Perplexity connection in the backend?

**Comment by inulute** [comment]
> Thanks for the app. What is the main advantage of it? I simply pin the website to the dock, the issue is that it breaks connection after a while, requiring me to refresh my login and captcha before my query gets answered. Does this app maintain the Perplexity connection in the backend? 
> 

Yes, the app maintains the connection in the background, which helps prevent needing to re-login frequently. At least, I haven't needed to log in repeatedly. Plus, there are more features coming soon that will further enhance your experience.

**Comment by rochakagrawal** [comment]
Unfortunately that’s not true. I had to refresh within 24 days as connection broke.  Seems it’s not different that a pinned website on the dock and acting as browser Sent from my  iphone On 30 Aug 2024, at 10:19 AM, inulute ***@***.***> wrote:﻿

Thanks for the app. What is the main advantage of it? I simply pin the website to the dock, the issue is that it breaks connection after a while, requiring me to refresh my login and captcha before my query gets answered. Does this app maintain the Perplexity connection in the backend?

Yes, the app maintains the connection in the background, which helps prevent needing to re-login frequently. At least, I haven't needed to log in repeatedly. Plus, there are more features coming soon that will further enhance your experience.

**Comment by inulute** [comment]
The timeout you're referring to is a server-side security feature that we can't modify since this app is unofficial. However, we are adding some additional features to enhance the app. Ultimately, it's up to you to decide what you find more preferable.
Thanks!
