### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by Cr1mepays** [inulute/perplexity-ai-app#15]
Hello,
Thanks for taking the time to create the perplexity ai desktop app.

Can you please add settings for users to change or disable the hotkeys?

Specifically Ctrl-6 is already in-use by default in some media player apps like 
https://github.com/clsid2/mpc-hc/releases (specifically it hides/unhides the video playlist)

MPC-HC (64-bit) and
MPC-BE (64-bit)

**Comment by inulute** [comment]
This feature is planned and will be included in future releases. Thanks!

**Comment by mike-lischke** [comment]
It's even worse: the perplexity app captures shift-cmd-P, which is one of the most used shortcuts in VS Code. I use it like 50 times a day. How can I just disable all short cuts of the app?

**Comment by inulute** [comment]
> It's even worse: the perplexity app captures shift-cmd-P, which is one of the most used shortcuts in VS Code. I use it like 50 times a day. How can I just disable all short cuts of the app?

Not yet. We'll soon push an update regarding customization of the shortcut keys.. Thanks!!

**Comment by inulute** [comment]
Hello, and thanks for the feedback!

In **Perplexity AI v3.0.0**, we’ve added **configurable keybinds** so you can customize or disable shortcuts to avoid conflicts with apps like MPC-HC and VS Code. Give it a try, and let us know how it works for you!

**Comment by inulute** [comment]
Hello, and thanks for the feedback!

In **Perplexity AI v3.0.0**, we’ve added **configurable keybinds** so you can customize shortcuts to avoid conflicts with apps like MPC-HC and VS Code. Give it a try, and let us know how it works for you!

**Comment by MentalGear** [comment]
> In **Perplexity AI v3.0.0**, we’ve added **configurable keybinds** so you can customize shortcuts to avoid conflicts with apps like MPC-HC and VS Code. Give it a try, and let us know how it works for you!

This is not well done. There is no settings menu items in the perplexity app, and it captures default high-usage shortcuts.
How to change those bindings ? The readme only states "configurable" but there is no description on how. Again, no settings window available no the app.

**Comment by MentalGear** [comment]
I'm gonna uninstall perplexity app because of this.

**Comment by inulute** [comment]
> > In **Perplexity AI v3.0.0**, we’ve added **configurable keybinds** so you can customize shortcuts to avoid conflicts with apps like MPC-HC and VS Code. Give it a try, and let us know how it works for you!
> 
> This is not well done. There is no settings menu items in the perplexity app, and it captures default high-usage shortcuts.
> How to change those bindings ? The readme only states "configurable" but there is no description on how. Again, no settings window available no the app.

Which version are you using?

**Comment by MentalGear** [comment]
With the new version, I found the settings now hidden under the sidebar icon. Still not good practice to overwrite common keyboard shortcuts, like VScode's command modal.

**Comment by MentalGear** [comment]
but I get that it's hard to find none-occupied shortcuts

**Comment by inulute** [comment]
> With the new version, I found the settings now hidden under the sidebar icon. Still not good practice to overwrite common keyboard shortcuts, like VScode's command modal.

Hey! I'm having trouble understanding what you mean. Could you share some screenshots to help clarify? Thanks!

**Comment by inulute** [comment]
> but I get that it's hard to find none-occupied shortcuts

Unfortunately, this isn’t just an issue with this application most software doesn't check if a shortcut is already being used by other programs.

**Comment by Cr1mepays** [comment]
Thing is, most apps don't capture hotkeys unless they are in the foreground. This one did. I'll test out the update. thanks for your efforts.

**Comment by retticle** [comment]
This should be reopened. On the Windows app there is no way to change the hotkeys and it takes over `Ctrl + Shift + P` which is used by basically every IDE. Was no developer involved in deciding the hotkeys?

There's no choice but to uninstall until resolved.

**Comment by inulute** [comment]
> This exact issue will be why I will be uninstalling the app as well! I'd love to use that functionality as an addition to powertoys run to search instantly but I want another hotkey. VSCode is more important to me than your service and this is totally counter intuitive. Issue should be reopened!

Hey, you can easily change the shortcut key. Just select the key you want to modify and press the new keyboard combination. It will register as the new shortcut key, Thanks!

https://github.com/user-attachments/assets/0e8f945e-57f5-4ff8-bcef-25354bc00bbf

**Comment by LZandbergen** [comment]
Not with the microsoft store version!

**Comment by LZandbergen** [comment]
Thanks though, now I understand why it was resolved

**Comment by MoriTanosuke** [comment]
I also ran into the incompability with vscode and changed the perplexity shortcut to something so convoluted that I won't hit it again.

Is there any way to remove a shortcut? I don't want to bind arbitrary key combinations just to avoid accidentally hitting the shortcut.

**Comment by inulute** [comment]
> I also ran into the incompability with vscode and changed the perplexity shortcut to something so convoluted that I won't hit it again.
> 
> Is there any way to remove a shortcut? I don't want to bind arbitrary key combinations just to avoid accidentally hitting the shortcut.

Hey! Sorry for the inconvenience. Right now, there’s no way to disable a specific shortcut, but I’m planning to release an update later this month that will add that option. Thanks for your patience!

**Comment by IsaiahSama** [comment]
Any updates on disabling the shortcut?
I finally used Vs Code for the first time in a while, since I returned to windows, and realized that my command palette has been hijacked by the Perplexity search bar, and for some reason, Windows doesn't have an easy way to view and disable shortcuts.

I've been exploring the settings for Perplexity for a while but I am not seeing any shortcut modifications as was mentioned in the previous comments. How disable?

**Comment by inulute** [comment]
> Any updates on disabling the shortcut? I finally used Vs Code for the first time in a while, since I returned to windows, and realized that my command palette has been hijacked by the Perplexity search bar, and for some reason, Windows doesn't have an easy way to view and disable shortcuts.
> 
> I've been exploring the settings for Perplexity for a while but I am not seeing any shortcut modifications as was mentioned in the previous comments. How disable? Update: I finally noticed the small keyboard icon with the shortcuts. However, I don't see the option to disable it. Either that, or have it only work when the app is focused.

Hi! Yes, the update has been released — please update to the latest version v4.0.0.

With this version, you can disable or customize shortcuts to suit your preferences.

You can also watch a tutorial on enabling and changing shortcuts here:


[pplx.inulute.com/shortcuts](https://pplx.inulute.com/shortcuts)


Thanks!
