### ISSUE TITLE
Run AppImage with option to pick between search and chat

### ISSUE THREAD

**Issue by BrianPulfer** [inulute/perplexity-ai-app#16]
Hi! Thanks for developing this, it's very useful!

I think there currently isn't an option to pick the option to either start "Perplexity AI Search" or "Perplexity AI Chat" from command line, so each time I run the AppImage I have to click "Perplexity AI Search", which is a bit annoying (I never use the chat option).

Would it be possible, for the AppImage, to add some CLI arguments, like `--chat` and `--search`, or `--mode search/chat`, to automatically run the selected mode?

**Comment by inulute** [comment]
> Would it be possible, for the AppImage, to add some CLI arguments, like `--chat` and `--search`, or `--mode search/chat`, to automatically run the selected mode?


Hi! We appreciate your feedback and will look into adding this. Thank you!

**Comment by inulute** [comment]
Hi! Thank you so much for your feedback and for finding Perplexity AI useful!

We’re excited to let you know that Perplexity AI v3.0.0 has just been released, and it includes several enhancements that address this very feature request. In v3.0.0, you can now set a default AI tool from the settings, so there’s no need to select "Perplexity AI Search" each time you launch the app.

While command-line arguments for mode selection aren’t implemented yet, we believe the default tool setting should greatly improve your experience. 


Thankyou!!
