### ISSUE TITLE
Unable to sign in via email

### ISSUE THREAD

**Issue by HidiH** [inulute/perplexity-ai-app#2]
When using email to sign in to perplexity, a private link is sent to that email address that then needs to be opened in the app. It is not possible to open the link in the perplexity ai app, so its not possible to login using email.

**Comment by inulute** [comment]
Thank you for bringing this to my attention. I will investigate it promptly.

**Comment by inulute** [comment]
Hey there! Good news – we just dropped Perplexity AI App v2.0.0! 🎉

Now you can open login links in the app.  Plus, we've jazzed up the UI! 🔥

Grab the update. Enjoy! 🌟

<div align='center' style="display: flex; justify-content: space-between; align-items: center;">
    <a href="https://www.pling.com/p/2107698/" style="margin-right: 10px;">
        <img src="https://img.shields.io/badge/Download-Latest-brightgreen?style=for-the-badge" alt="Latest Release">
    </a> &nbsp
    <a href="https://github.com/inulute/perplexity-ai-app/releases">
        <img src="https://img.shields.io/github/v/release/inulute/perplexity-ai-app?color=brightgreen&include_prereleases&label=Changelog&style=for-the-badge" alt="Changelog">
    </a>
</div>

**Comment by HidiH** [comment]
Thank you. 
I can confirm it works.
