### ISSUE TITLE
Shortcut buttons still function even if the app is closed

### ISSUE THREAD

**Issue by Akusho** [inulute/perplexity-ai-app#21]
Hello,
This one was a doozy. Took me some time to understand what the hell was happening.

The latest Perplexity 3.1.1 has keyboard shortcuts that are enabled by default.
The issue is, that even if the app is closed, the shortcuts are still monitored.

So, for example, if you have shortcuts in other apps, such as Firefox, where CTRL+Shift+T opens the last closed tab, these will no longer work in Firefox, because they are reserved by Perplexity app. Another example is CTRL+1 in Spyder IDE, which comments a block of code. This will also be reserved by Perplexity app and will not operate within Spyder.

I believe the correct operation of the shortcuts would be enabling them only when Perplexity app is in focus. Or, at least, have an option to disable them altogether

I changed the shortcuts to longer combinations of buttons and this solved the issues I was having.

**Comment by nerdCopter** [comment]
- +1
- request ability to disable shortcut entirely. particularly Ctrl-R stops bash reverse-search (Linux).
- not running appimage until this exists.

**Comment by inulute** [comment]
> - request ability to disable shortcut entirely. particularly Ctrl-R hijacks bash reverse-search (Linux).
> - not running appimage until this exists.




Thanks for the suggestion! We'll consider adding an option to disable the shortcut entirely.

**Comment by inulute** [comment]
Hey! Please update to v3.2.0.

Thanks!!

**Comment by nerdCopter** [comment]
An ability to just clear individual shortcuts as a "disable", might have been better than a global button to disabling all shortcuts. Never the less, the option was welcomed.

**Comment by inulute** [comment]
> An ability to just clear individual shortcuts as a "disable", might have been better than a global button to disabling all shortcuts. Never the less, the option was welcomed.

Thanks for the suggestion. We'll try to add individual Toggle.
