### ISSUE TITLE
Unable to delete threads 

### ISSUE THREAD

**Issue by lammel-hub** [inulute/perplexity-ai-app#22]
Hi,
With the latest release I am unable to delete threads. Thd function is there, but it does not execute. It worked in v2 

OS: Win 11, latest release

**Comment by inulute** [comment]
Thanks for reporting this! We’re prioritizing this for the next update.

**Comment by inulute** [comment]
Hey, please update to v3.2.0. Thanks!!

**Comment by lammel-hub** [comment]
tested in windows 11 and Linux Mint 22 - works (and other nice tweaks noted too)
