### ISSUE TITLE
Unable to close app

### ISSUE THREAD

**Issue by lammel-hub** [inulute/perplexity-ai-app#23]
Hi,
With the latest release I am unable to close down the app. It worked in v2.x.x

- When clicking "x" it is only minimized to icon tray/system tray. 
- I thought a right-click on that icon would offer the option to shut-down the app, but that is not possible.
- A right-click on the taskbar icon/panel icon does not offer a close/shut-down option either. 

(Added comment: When looking at issue #21, perhaps that is a consequence of the behavior described here in issue #23)

OS: Win 11, latest release
OS: Linux Mint 22, Cinnamon Edition

**Comment by nerdCopter** [comment]
- +1
- request proper exit/quit

**Comment by inulute** [comment]
Thanks for your feedback! A proper fix will be out in 2-3 days. Appreciate your patience!

**Comment by fronald** [comment]
I downloaded the application's source code to implement "Quit" as a context menu in the system tray for my use. After finishing my implementation, I would send the PR to contribute. But I came across obfuscated source codes. If the application is open source and under the GPL-v3 license, why are the sources obfuscated? Is there a branch with unobfuscated sources?

I really think it's a security issue when an open-source application isn't truly open. I don't know what these codes are doing in an application that doesn't have an option to be closed. The GPL-v3 license can't even be applied to an application whose sources are obfuscated.

![image](https://github.com/user-attachments/assets/26e61558-1a27-458b-96c5-487e0f453824)

**Comment by inulute** [comment]
Hello, thank you for your interest in contributing! The repository currently contains obfuscated code as a temporary measure. However, the application itself is compiled using unobfuscated code. And, the unobfuscated source code will be published publicly with the next release :)  

If you’d like to contribute and help expedite the release of the source code, feel free to reach out via PM at [inulute](https://t.me/inulute).

**Comment by fronald** [comment]
Sorry. I can't trust on obfuscate code.

Better try https://github.com/Wiselabs/simplexity

**Comment by lammel-hub** [comment]
@fronald great tip! It looks like its only for linux, though. Will it be available for Win/MacOS too, or did I misunderstand the release? That would be a killer app!

**Comment by inulute** [comment]
> Sorry. I can't trust on obfuscate code.

You’re absolutely right, I wouldn’t trust obfuscated code either. I’ll release the code today. Appreciate your input!

> Better try https://github.com/Wiselabs/simplexity

BTW nice app :⁠-⁠)

**Comment by inulute** [comment]
Hey, please update to v3.2.0 . Thanks!!

**Comment by lammel-hub** [comment]
tested in windows 11 and Linux Mint 22 - works (and other nice tweaks noted too)

**Comment by fronald** [comment]
> @fronald great tip! It looks like its only for linux, though. Will it be available for Win/MacOS too, or did I misunderstand the release? That would be a killer app!

Yes! You can create a new GitHub issue to create this packages? I will do it with great pleasure!
