### ISSUE TITLE
Unable to decline cookies in v3.x.x ?

### ISSUE THREAD

**Issue by lammel-hub** [inulute/perplexity-ai-app#24]
In ver 2.x.x hhe user could opt-out from cookies, in accordance with GDPR.

With version 3.x.x this option is not evident. Is it set to opt-out by default, or is the setting moved within the app?

Thanks!

**Comment by inulute** [comment]
Thanks for bringing this up! We'll look into this.

**Comment by inulute** [comment]
Hey! Please check if it's fixed in v3.2.0. Thanks!!

**Comment by lammel-hub** [comment]
tested in windows 11 and Linux Mint 22 - works (and other nice tweaks noted too)
