### ISSUE TITLE
backup all the messages feature request

### ISSUE THREAD

**Issue by nnWhisperer** [inulute/perplexity-ai-app#4]
Hello,
The normal perplexity ai web page doesn't provide a way to back up all messages. If this app provides a way to backup messages, it would be popular IMHO, instead of the webpage, people would prefer this app. Thank you

**Comment by inulute** [comment]
Heyy! Do you mean saving the entire conversation as a PDF or something similar?

**Comment by nnWhisperer** [comment]
Not the single conversation but all the conversations occurred using the app, as a simple json backup file. Thanks

**Comment by inulute** [comment]
> Not the single conversation but all the conversations occurred using the app, as a simple json backup file. Thanks

Do you have any ideas on how I could implement it? Thanks!
