### ISSUE TITLE
How to sign into perplexity?

### ISSUE THREAD

**Issue by NateHutchison** [inulute/perplexity-ai-app#5]
I've tried signing in but even when I confirm email it doesn't register in app.  Same issue in the Noi app as well.  Any ideas?

**Comment by inulute** [comment]
Ah, looks like Perplexity AI has revamped their login process.

I'll try to push an update to accommodate this change.

**Comment by NateHutchison** [comment]
awesome thanks!  I'll be on the lookout for it.

**Comment by TheWood1978** [comment]
Same here, unable to login using the app, shame.

Hope its resolved soon.

**Comment by SUPRVLLAN** [comment]
Any progress on this?

**Comment by inulute** [comment]
Sorry for the delay. I have exams going on at the moment. I'll work on a fix for the login issue as soon as I get some free time. 🙂

**Comment by alexmaccabi** [comment]
Don't know about the issue, 
had no issue with sign-in and works great !

**Comment by inulute** [comment]
The login issue has been resolved. Thanks!

**Comment by Jaykurb** [comment]
I am having this issue now. Is there a way around this, or has Perplexity revamped their login process again?

**Comment by Jaykurb** [comment]
> > I am having this issue now. Is there a way around this, or has Perplexity revamped their login process again?
> 
> Let me check on that. For the time being, please use 'Sign in with Google'.

I got around it by adding my email inbox as a URL and signing in with the Noi app

**Comment by inulute** [comment]
Hey! Check version 2.2.0, we have resolved the sign-in issue. You should now be able to log in using your email without any problems. Thanks!
