### ISSUE TITLE
Open Links in Firefox/Safari + Auto Update feature?

### ISSUE THREAD

**Issue by x0ceo** [inulute/perplexity-ai-app#6]
I've been an avid user of this project and truly appreciate the work that's been put into it—it's become an indispensable tool in my daily workflow. As I continue to integrate it into my routine, I've noticed a couple of enhancements that could significantly improve the user experience.
Firstly, the ability to open links in external browsers and setting a default browser to open links with would offer a more seamless navigation experience, allowing users to access additional information without leaving the app. This feature would not only enhance usability but also align with common user expectations for app interactions.
Secondly, an in-app update mechanism would streamline the process of keeping the app current with the latest features and fixes. It would provide convenience by reducing the steps needed to maintain the app, ensuring that users always have access to the best possible version without manual intervention.
Implementing these features would undoubtedly elevate the overall functionality and user satisfaction. I'm looking forward to seeing how the app evolves and would be thrilled to see these additions in future updates. Keep up the fantastic work!

**Comment by inulute** [comment]
1. Adding an option to open links in the default browser sounds like a valuable enhancement. I'll definitely look into implementing this feature to enhance the user experience.

2. While I understand the appeal of a seamless in-app update mechanism, I rely on hosting files on Pling, where each download contributes to supporting the project. Your support through these downloads helps keep the project going, as unfortunately, donations are not a consistent source of income.

**Comment by x0ceo** [comment]
Multiple tabs/windows would be nice too! This shit is super slick i just need like two or three instances when im working on stuff

**Comment by inulute** [comment]
> Multiple tabs/windows would be nice too! This shit is super slick i just need like two or three instances when im working on stuff

Absolutely! While I work on pushing an update, I'd recommend checking out [AI-Gate](https://aigate.inulute.com). It's another handy tool that might complement your workflow while you wait for the new feature. 

Thanks for the suggestion!

**Comment by x0ceo** [comment]
I use that one as well as MindMac

**Comment by inulute** [comment]
Hey, checkout version 2.2.0, all external links now open in your default browser. Thanks!
