### ISSUE TITLE
Perplexity Update Feature

### ISSUE THREAD

**Issue by RajPabnani03** [inulute/perplexity-ai-app#9]
In the Help Section their should be an option of Update Log, Report Bug, Developer Tools and most importantly Update App.

**Comment by inulute** [comment]
Please elaborate

**Comment by RajPabnani03** [comment]
there is no way to update the perplexity application directly from the app itself . Please provide a way so that the application can get update without pulling the recent updates by git pull request.

**Comment by inulute** [comment]
> there is no way to update the perplexity application directly from the app itself . Please provide a way so that the application can get update without pulling the recent updates by git pull request.

I’m aware that updating the application directly from within the app would be ideal. However, the current method helps generate some income, which is crucial for sustaining ongoing projects, as donations are not enough to cover the costs. I appreciate your understanding and support in this regard.
